---
apiVersion: v1
kind: Namespace
metadata:
  name: fred

---
apiVersion: apps/v1
kind:       Deployment
metadata:
  name: nginx
  namespace: fred
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name:            nginx
        image:           nginx:1.15-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80