---
kind:       Deployment
apiVersion: apps/v1
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name:            jaeger
        image:           jaegertracing/all-in-one:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name:          http
          protocol:      TCP
          containerPort: 16686
        - name:          udp
          protocol:      UDP
          containerPort: 6831
---
kind:       Service
apiVersion: v1
metadata:
  name: jaeger
spec:
  type: NodePort
  selector:
    app: jaeger
  ports:
    - name:       http
      protocol:   TCP
      nodePort:   30600
      port:       16686
    - name:       udp
      protocol:   UDP
      nodePort:   30601
      port:       6831
