apiVersion: apps/v1
kind:       Deployment
metadata:
  name: hangman2
  labels:
    app: hangman2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hangman2
  template:
    metadata:
      labels:
        app: hangman2
    spec:
      containers:
      - name:            hangman2
        image:           k8sland/go-hangman-svc:0.0.1
        imagePullPolicy: IfNotPresent
        args:            ["/app/hangman", "-d", "dictionary2:4002"]
        resources:
          requests:
            cpu:    100m
            memory: 4Mi
          limits:
            cpu:    200m
            memory: 8Mi
        ports:
        - name:          http
          containerPort: 5000
---
apiVersion: v1
kind:       Service
metadata:
  name: hangman2
  labels:
    app: hangman2
spec:
  type: ClusterIP
  selector:
    app: hangman2
  ports:
    - name:       http
      protocol:   TCP
      port:       80
      targetPort: http
