apiVersion: apps/v1
kind:       Deployment
metadata:
  name: dictionary
  labels:
    app: dictionary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dictionary
  template:
    metadata:
      labels:
        app: dictionary
    spec:
      containers:
      - name: dictionary
        image: k8sland/dictionary-svc-go:0.0.2
        command: ['/app/dictionary', '-a', '/var/dictionary/words', '-d', 'trump.txt']
        ports:
        - name: http
          containerPort: 4000
        volumeMounts:
        - name:      dictionary
          mountPath: /var/dictionary
      initContainers:
      - name:    git
        image:   luzhzh/git-client
        command: ['sh', '-c', 'rm -rf /var/dictionary/words && git clone https://github.com/k8sland/dictionaries.git /var/dictionary/words']
        volumeMounts:
        - name:      dictionary
          mountPath: /var/dictionary
      volumes:
      - name: dictionary
        hostPath:
          path: /home/docker/dictionary
---
apiVersion: v1
kind:       Service
metadata:
  name: dictionary
spec:
  type: NodePort
  selector:
    app: dictionary
  ports:
  - name:       http
    port:       4000
    nodePort:   30400
    targetPort: http