apiVersion: apps/v1
kind:       Deployment
metadata:
  name: hangman
  labels:
    app: hangman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hangman
  template:
    metadata:
      labels:
        app: hangman
    spec:
      containers:
      - name:            hangman
        image:           k8sland/go-hangman-prom-svc:0.0.1
        imagePullPolicy: IfNotPresent
        args:            ["/app/hangman", "-d", "dictionary:4000"]
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 5
          periodSeconds:       10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 5
          periodSeconds:       10
        resources:
          requests:
            cpu:    100m
            memory: 4Mi
          limits:
            cpu:    200m
            memory: 8Mi
        ports:
        - name:          http
          containerPort: 5000
---
apiVersion: v1
kind:       Service
metadata:
  name: hangman
  labels:
    app: hangman
spec:
  type: NodePort
  selector:
    app: hangman
  ports:
    - name:       http
      protocol:   TCP
      nodePort:   30500
      port:       5000
