apiVersion: v1
kind:       Service
metadata:
  name:     nginx
  labels:
    app:    nginx
spec:
  # Indicate headless service
  clusterIP: None
  selector:
    app: nginx
  ports:
  - port: 80
---
apiVersion: apps/v1
kind:       StatefulSet
metadata:
  name:     nginx
spec:
  serviceName: nginx
  replicas:    3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
