---
apiVersion: v1
kind:       Service
metadata:
  name: dictionary
spec:
  type: NodePort
  # Select your dictionary pods here
  !!CHANGE_ME!!
  ports:
    - name:       http
      protocol:   TCP
      nodePort:   30400
      port:       4000