kind:       Deployment
apiVersion: apps/v1
metadata:
  name: dictionary-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dictionary
      rev: v1
  template:
    metadata:
      labels:
        app: dictionary
        rev: v1
    spec:
      containers:
      - name:            dictionary
        image:           k8sland/go-dictionary-svc:0.0.1
        imagePullPolicy: IfNotPresent
        args:            ['/app/dictionary', '-d', 'trump.txt']
        resources:
          requests:
            cpu:    100m
            memory: 4Mi
          limits:
            cpu:    200m
            memory: 8Mi
        ports:
        - name:          http
          containerPort: 4000